org: matheusmski
app: aws-node-http-api
service: aws-node-http-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action: '*'
          Resource: '*'
plugins:
  - serverless-offline

custom:
  devRegion: 'us-east-1'

functions:
  createUser:
    handler: src/createUser/handler.createUser
    environment: 
      DEV_REGION: ${self:custom.devRegion}
    events:
      - httpApi:
          method: POST
          path: /user
          cors: true

  readUser:
    handler: src/readUser/handler.readUser
    environment: 
      DEV_REGION: ${self:custom.devRegion}
    events:
      - httpApi:
          method: GET
          path: /user/{email}
          cors: true          

resources: 
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: usersTable
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
