org: matheusmski
app: aws-node-http-api
service: aws-node-http-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action: '*'
          Resource: '*'
plugins:
  - serverless-offline
  - serverless-auto-swagger

custom:
  devRegion: 'us-east-1'
  documentation:
    version: '1'
    title: 'API Teste TON'
    description: 'Teste tecnico TON'
    models: {}

functions:

  createUser:
    handler: src/dynamoDb/createUser/handler.createUser
    environment: 
      DEV_REGION: ${self:custom.devRegion}
    events:
      - httpApi:
          method: POST
          path: /user
          cors: true

  readUser:
    handler: src/dynamoDb/readUser/handler.readUser
    environment: 
      DEV_REGION: ${self:custom.devRegion}
    events:
      - httpApi:
          method: GET
          path: /user/{email}
          cors: true    

  incrementCount:
    handler: src/countApi/implement/handler.count
    environment: 
    events:
      - httpApi:
          method: GET
          path: /count/increment
          cors: true

  getCount:
    handler: src/countApi/read/handler.read
    environment: 
    events:
      - httpApi:
          method: GET
          path: /count
          cors: true     

resources: 
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: usersTable
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
